/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkoutsRouteImport } from './routes/workouts'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as CreateWorkoutRouteImport } from './routes/create-workout'
import { Route as ActiveWorkoutRouteImport } from './routes/active-workout'
import { Route as IndexRouteImport } from './routes/index'

const WorkoutsRoute = WorkoutsRouteImport.update({
  id: '/workouts',
  path: '/workouts',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateWorkoutRoute = CreateWorkoutRouteImport.update({
  id: '/create-workout',
  path: '/create-workout',
  getParentRoute: () => rootRouteImport,
} as any)
const ActiveWorkoutRoute = ActiveWorkoutRouteImport.update({
  id: '/active-workout',
  path: '/active-workout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/active-workout': typeof ActiveWorkoutRoute
  '/create-workout': typeof CreateWorkoutRoute
  '/progress': typeof ProgressRoute
  '/settings': typeof SettingsRoute
  '/workouts': typeof WorkoutsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/active-workout': typeof ActiveWorkoutRoute
  '/create-workout': typeof CreateWorkoutRoute
  '/progress': typeof ProgressRoute
  '/settings': typeof SettingsRoute
  '/workouts': typeof WorkoutsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/active-workout': typeof ActiveWorkoutRoute
  '/create-workout': typeof CreateWorkoutRoute
  '/progress': typeof ProgressRoute
  '/settings': typeof SettingsRoute
  '/workouts': typeof WorkoutsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/active-workout'
    | '/create-workout'
    | '/progress'
    | '/settings'
    | '/workouts'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/active-workout'
    | '/create-workout'
    | '/progress'
    | '/settings'
    | '/workouts'
  id:
    | '__root__'
    | '/'
    | '/active-workout'
    | '/create-workout'
    | '/progress'
    | '/settings'
    | '/workouts'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActiveWorkoutRoute: typeof ActiveWorkoutRoute
  CreateWorkoutRoute: typeof CreateWorkoutRoute
  ProgressRoute: typeof ProgressRoute
  SettingsRoute: typeof SettingsRoute
  WorkoutsRoute: typeof WorkoutsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workouts': {
      id: '/workouts'
      path: '/workouts'
      fullPath: '/workouts'
      preLoaderRoute: typeof WorkoutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-workout': {
      id: '/create-workout'
      path: '/create-workout'
      fullPath: '/create-workout'
      preLoaderRoute: typeof CreateWorkoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/active-workout': {
      id: '/active-workout'
      path: '/active-workout'
      fullPath: '/active-workout'
      preLoaderRoute: typeof ActiveWorkoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActiveWorkoutRoute: ActiveWorkoutRoute,
  CreateWorkoutRoute: CreateWorkoutRoute,
  ProgressRoute: ProgressRoute,
  SettingsRoute: SettingsRoute,
  WorkoutsRoute: WorkoutsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
